services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: vahyna
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - '5435:5432'
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -q -d vahyna -U root' ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '3335:3333'
    volumes:
      - uploads:/app/uploads
    depends_on:
      db:
        condition: service_healthy
    develop: #Il faut l'enlever pour la PROD
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - node_modules/
            - .git/
            - .vscode/       # Exclure les fichiers spécifiques à Visual Studio Code
            - .env.example  # Exclure les fichiers d'exemple de configuration
            - .DS_Store     # Exclure les fichiers de système macOS
            - build/        # Exclure les fichiers de build
            - dist/         # Exclure les fichiers de distribution
            - logs/         # Exclure les fichiers de logs
            - tmp/          # Exclure les fichiers temporaires
        - action: rebuild
          path: package.json
          target: /app
volumes:
  postgres-data:
  uploads:
