name: deploy
on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest
    env:
      SERVICES: db app
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy the new image
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: |
            cd /srv/vahyna/api-test/
            docker pull ghcr.io/ewiiz/api-vahyna:latest
            docker-compose up -d $SERVICES
